"""
Day 020: Digital Signatures (ECDSA) from Scratch

A complete implementation of the Elliptic Curve Digital Signature Algorithm
using the secp256k1 curve (same as Bitcoin/Ethereum). Built from first
principles — no cryptographic libraries for the core math.
"""

import hashlib
import secrets
from dataclasses import dataclass
from typing import Optional, Tuple


# =============================================================================
# secp256k1 Curve Parameters
# =============================================================================
# These are the exact parameters used by Bitcoin and Ethereum.
# The curve equation is y² = x³ + 7 (mod p).

# The prime defining the finite field F_p.
# All arithmetic is done modulo this number.
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F

# Curve coefficients: y² = x³ + ax + b
A = 0
B = 7

# Generator point G — a fixed point on the curve that generates the cyclic group.
# Every valid public key is some multiple of G.
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8

# Order of the generator point — the number of points in the subgroup generated by G.
# After n additions of G, you get back to the identity (point at infinity).
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141


# =============================================================================
# Modular Arithmetic Helpers
# =============================================================================

def mod_inverse(a: int, m: int) -> int:
    """
    Compute the modular multiplicative inverse of a modulo m.

    Uses the extended Euclidean algorithm: finds x such that a*x ≡ 1 (mod m).
    This is essential because division doesn't exist in modular arithmetic —
    instead of dividing by a, we multiply by a's inverse.

    Time complexity: O(log m) — same as the Euclidean GCD algorithm.

    Could also use Fermat's little theorem (a^(m-2) mod m) since m is prime,
    but extended GCD is faster in practice and works for non-prime moduli too.
    """
    if a < 0:
        a = a % m

    # Extended Euclidean Algorithm
    # Maintains: old_r = old_s * a + old_t * m (we only need old_s)
    old_r, r = a, m
    old_s, s = 1, 0

    while r != 0:
        quotient = old_r // r
        old_r, r = r, old_r - quotient * r
        old_s, s = s, old_s - quotient * s

    if old_r != 1:
        raise ValueError(f"{a} has no inverse modulo {m}")

    return old_s % m


# =============================================================================
# Elliptic Curve Point Arithmetic
# =============================================================================

@dataclass
class Point:
    """
    A point on the secp256k1 elliptic curve.

    Points are either:
    - A concrete (x, y) coordinate pair on the curve
    - The "point at infinity" (identity element), represented by x=None, y=None

    The point at infinity acts like zero in addition: P + O = P.
    It's the result of adding a point to its own negation (P + (-P) = O).
    """
    x: Optional[int]
    y: Optional[int]

    @property
    def is_infinity(self) -> bool:
        return self.x is None and self.y is None

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Point):
            return NotImplemented
        return self.x == other.x and self.y == other.y

    def __repr__(self) -> str:
        if self.is_infinity:
            return "Point(infinity)"
        # Show first/last 8 hex chars for readability
        x_hex = f"{self.x:064x}"
        y_hex = f"{self.y:064x}"
        return f"Point(x={x_hex[:8]}...{x_hex[-8:]}, y={y_hex[:8]}...{y_hex[-8:]})"


# The identity element — like zero for point addition
INFINITY = Point(None, None)

# The generator point
G = Point(GX, GY)


def point_add(p1: Point, p2: Point) -> Point:
    """
    Add two points on the secp256k1 curve.

    This is the fundamental group operation. Three cases:
    1. Either point is infinity → return the other (identity property)
    2. Points have same x but different y → they're inverses, return infinity
    3. Otherwise → compute the line through them, find third intersection, reflect

    For point doubling (p1 == p2), we use the tangent line instead.

    All arithmetic is mod P to stay in the finite field.
    """
    # Case 1: Identity element
    if p1.is_infinity:
        return p2
    if p2.is_infinity:
        return p1

    # Case 2: Points are inverses (same x, opposite y)
    # In F_p, "opposite y" means y1 + y2 ≡ 0 (mod P), i.e., y2 = P - y1
    if p1.x == p2.x and p1.y != p2.y:
        return INFINITY

    # Case 3a: Point doubling (tangent line)
    if p1.x == p2.x and p1.y == p2.y:
        # Slope of the tangent: dy/dx = (3x² + a) / (2y)
        # Division becomes multiplication by modular inverse
        slope = (3 * p1.x * p1.x + A) * mod_inverse(2 * p1.y, P) % P
    else:
        # Case 3b: Distinct points (secant line)
        # Slope = (y2 - y1) / (x2 - x1)
        slope = (p2.y - p1.y) * mod_inverse(p2.x - p1.x, P) % P

    # New point coordinates from the line-curve intersection
    # x3 = slope² - x1 - x2 (mod P)
    x3 = (slope * slope - p1.x - p2.x) % P
    # y3 = slope * (x1 - x3) - y1 (mod P)
    y3 = (slope * (p1.x - x3) - p1.y) % P

    return Point(x3, y3)


def scalar_multiply(k: int, point: Point) -> Point:
    """
    Compute k * point using the double-and-add algorithm.

    This is analogous to fast exponentiation (square-and-multiply):
    - Write k in binary: k = b_n b_{n-1} ... b_1 b_0
    - Scan bits from most significant to least
    - For each bit: double the accumulator
    - If the bit is 1: also add the base point

    Example: 13 * G = (1101)₂ * G
      Start with O (infinity)
      Bit 1: double(O) = O, add G → G
      Bit 1: double(G) = 2G, add G → 3G
      Bit 0: double(3G) = 6G
      Bit 1: double(6G) = 12G, add G → 13G

    Time complexity: O(log k) point operations — crucial because k is ~256 bits.
    Doing k sequential additions would take ~2²⁵⁶ operations (heat death of universe).

    WARNING: This implementation is NOT constant-time and leaks information about k
    through timing side channels. Production code must use constant-time algorithms
    (e.g., Montgomery ladder) to prevent private key extraction via timing attacks.
    """
    # Reduce k modulo the curve order — k*G = (k mod n)*G since G has order n
    k = k % N

    if k == 0:
        return INFINITY

    result = INFINITY
    addend = point

    while k:
        if k & 1:  # Current bit is 1
            result = point_add(result, addend)
        addend = point_add(addend, addend)  # Double
        k >>= 1  # Shift to next bit

    return result


# =============================================================================
# ECDSA: Key Generation, Signing, Verification
# =============================================================================

def hash_message(message: str) -> int:
    """
    Hash a message to an integer for signing.

    Uses SHA-256 (same as Bitcoin). The hash is interpreted as a big-endian
    integer and truncated to the bit-length of the curve order n.
    For secp256k1, n is 256 bits and SHA-256 produces 256 bits, so no
    truncation is needed — but we include the logic for correctness.
    """
    digest = hashlib.sha256(message.encode('utf-8')).digest()
    z = int.from_bytes(digest, 'big')

    # Truncate to the bit-length of n (for secp256k1 this is a no-op)
    bit_length = N.bit_length()
    z_bit_length = z.bit_length()
    if z_bit_length > bit_length:
        z >>= (z_bit_length - bit_length)

    return z


def generate_keypair() -> Tuple[int, Point]:
    """
    Generate an ECDSA key pair.

    Private key: a random integer d in [1, n-1]
    Public key: the point Q = d * G

    The security rests on the discrete logarithm problem:
    given Q and G, finding d is computationally infeasible.

    Returns:
        (private_key, public_key) tuple
    """
    # Generate a cryptographically secure random private key
    # secrets module uses the OS CSPRNG — suitable for key material
    private_key = secrets.randbelow(N - 1) + 1  # Range: [1, N-1]

    # Public key = private_key * G (scalar multiplication)
    public_key = scalar_multiply(private_key, G)

    return private_key, public_key


def sign(message: str, private_key: int) -> Tuple[int, int]:
    """
    Sign a message using ECDSA.

    Steps:
    1. Hash the message to get z
    2. Pick a random nonce k (MUST be unique per signature)
    3. Compute R = k*G, set r = R.x mod n
    4. Compute s = k⁻¹ * (z + r*d) mod n
    5. Return (r, s)

    The nonce k is the most security-critical value. If an attacker learns k
    for even one signature, they can compute the private key directly.
    If k is reused across two signatures, the private key leaks algebraically.

    In production, use RFC 6979 deterministic nonces instead of random ones.
    """
    z = hash_message(message)

    while True:
        # Step 2: Generate a random nonce k
        k = secrets.randbelow(N - 1) + 1

        # Step 3: Compute the curve point R = k * G
        R = scalar_multiply(k, G)
        r = R.x % N

        if r == 0:
            # Extremely unlikely but must handle — try another k
            continue

        # Step 4: Compute s = k⁻¹ * (z + r * private_key) mod N
        # This binds the message hash (z), the random point (r), and
        # the private key (d) together in a way that only k⁻¹ can untangle
        k_inv = mod_inverse(k, N)
        s = (k_inv * (z + r * private_key)) % N

        if s == 0:
            # Also extremely unlikely
            continue

        return (r, s)


def verify(message: str, signature: Tuple[int, int], public_key: Point) -> bool:
    """
    Verify an ECDSA signature.

    Steps:
    1. Check r, s are in [1, n-1]
    2. Hash the message to get z
    3. Compute w = s⁻¹ mod n
    4. Compute u₁ = z*w mod n, u₂ = r*w mod n
    5. Compute R' = u₁*G + u₂*Q
    6. Valid iff R'.x mod n == r

    Why this works (the beautiful algebra):
      u₁*G + u₂*Q
      = (z*s⁻¹)*G + (r*s⁻¹)*(d*G)
      = s⁻¹*(z + r*d)*G
      = (k⁻¹*(z + r*d))⁻¹ * (z + r*d) * G    [since s = k⁻¹*(z + r*d)]
      = k * G
      = R

    So R'.x should equal r = R.x mod n. QED.
    """
    r, s = signature

    # Step 1: Range check
    if not (1 <= r < N and 1 <= s < N):
        return False

    # Step 2: Hash the message
    z = hash_message(message)

    # Step 3: Compute w = s⁻¹ mod n
    w = mod_inverse(s, N)

    # Step 4: Compute u1, u2
    u1 = (z * w) % N
    u2 = (r * w) % N

    # Step 5: Compute R' = u1*G + u2*Q
    # This is the most expensive step — two scalar multiplications and one addition
    point1 = scalar_multiply(u1, G)
    point2 = scalar_multiply(u2, public_key)
    R_prime = point_add(point1, point2)

    if R_prime.is_infinity:
        return False

    # Step 6: Check r == R'.x mod n
    return R_prime.x % N == r


# =============================================================================
# Nonce Reuse Attack Demonstration
# =============================================================================

def sign_with_known_nonce(message: str, private_key: int, k: int) -> Tuple[int, int]:
    """
    Sign with a specified nonce k. NEVER do this in production.
    Used here solely to demonstrate the nonce-reuse vulnerability.
    """
    z = hash_message(message)
    R = scalar_multiply(k, G)
    r = R.x % N
    k_inv = mod_inverse(k, N)
    s = (k_inv * (z + r * private_key)) % N
    return (r, s)


def nonce_reuse_attack(
    msg1: str, sig1: Tuple[int, int],
    msg2: str, sig2: Tuple[int, int]
) -> Optional[int]:
    """
    Extract the private key from two signatures that used the same nonce.

    Given:
      s₁ = k⁻¹(z₁ + r·d) mod n
      s₂ = k⁻¹(z₂ + r·d) mod n

    Subtract:
      s₁ - s₂ = k⁻¹(z₁ - z₂) mod n

    Solve for k:
      k = (z₁ - z₂) · (s₁ - s₂)⁻¹ mod n

    Then recover d:
      d = (s₁·k - z₁) · r⁻¹ mod n

    This is exactly how the PS3 master signing key was stolen in 2010.
    """
    r1, s1 = sig1
    r2, s2 = sig2

    # Both signatures must have the same r (same nonce → same R → same r)
    if r1 != r2:
        print("  Signatures don't share the same r — different nonces were used.")
        return None

    z1 = hash_message(msg1)
    z2 = hash_message(msg2)

    # Recover the nonce k
    # k = (z1 - z2) * (s1 - s2)⁻¹ mod n
    ds = (s1 - s2) % N
    dz = (z1 - z2) % N
    k_recovered = (dz * mod_inverse(ds, N)) % N

    # Recover the private key d
    # d = (s1 * k - z1) * r⁻¹ mod n
    r_inv = mod_inverse(r1, N)
    d_recovered = ((s1 * k_recovered - z1) * r_inv) % N

    return d_recovered


# =============================================================================
# Main — Demonstration
# =============================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("ECDSA Digital Signatures — From Scratch")
    print("=" * 70)

    # --- Verify the generator point is on the curve ---
    print("\n[1] Verifying generator point G is on secp256k1...")
    lhs = pow(GY, 2, P)
    rhs = (pow(GX, 3, P) + B) % P
    assert lhs == rhs, "Generator point is NOT on the curve!"
    print(f"  y² mod p = {hex(lhs)[:20]}...")
    print(f"  x³+7 mod p = {hex(rhs)[:20]}...")
    print("  Match! G is on the curve.")

    # --- Key generation ---
    print("\n[2] Generating key pair...")
    private_key, public_key = generate_keypair()
    print(f"  Private key (d): {hex(private_key)[:20]}...{hex(private_key)[-8:]}")
    print(f"  Public key (Q):  {public_key}")

    # Verify public key is on the curve
    lhs = pow(public_key.y, 2, P)
    rhs = (pow(public_key.x, 3, P) + B) % P
    assert lhs == rhs, "Public key is NOT on the curve!"
    print("  Public key verified on curve.")

    # --- Signing ---
    message = "Send 1 BTC to Alice"
    print(f"\n[3] Signing message: '{message}'")
    signature = sign(message, private_key)
    r, s = signature
    print(f"  r = {hex(r)[:20]}...{hex(r)[-8:]}")
    print(f"  s = {hex(s)[:20]}...{hex(s)[-8:]}")

    # --- Verification ---
    print("\n[4] Verifying signature...")
    is_valid = verify(message, signature, public_key)
    print(f"  Valid: {is_valid}")
    assert is_valid, "Signature should be valid!"

    # --- Tampered message ---
    tampered = "Send 100 BTC to Alice"
    print(f"\n[5] Verifying with tampered message: '{tampered}'")
    is_valid_tampered = verify(tampered, signature, public_key)
    print(f"  Valid: {is_valid_tampered}")
    assert not is_valid_tampered, "Tampered message should NOT verify!"

    # --- Wrong key ---
    print("\n[6] Verifying with wrong public key...")
    _, wrong_key = generate_keypair()
    is_valid_wrong_key = verify(message, signature, wrong_key)
    print(f"  Valid: {is_valid_wrong_key}")
    assert not is_valid_wrong_key, "Wrong key should NOT verify!"

    # --- Nonce reuse attack ---
    print("\n[7] Demonstrating nonce reuse attack...")
    print("  (This is why nonce security is critical!)")

    # Sign two different messages with the SAME nonce — catastrophic!
    reuse_nonce = secrets.randbelow(N - 1) + 1
    msg_a = "Transfer 0.5 ETH to Bob"
    msg_b = "Transfer 0.5 ETH to Charlie"

    sig_a = sign_with_known_nonce(msg_a, private_key, reuse_nonce)
    sig_b = sign_with_known_nonce(msg_b, private_key, reuse_nonce)

    print(f"\n  Message A: '{msg_a}'")
    print(f"  Signature A: r={hex(sig_a[0])[:16]}..., s={hex(sig_a[1])[:16]}...")
    print(f"\n  Message B: '{msg_b}'")
    print(f"  Signature B: r={hex(sig_b[0])[:16]}..., s={hex(sig_b[1])[:16]}...")

    print(f"\n  Notice both signatures have the same r! (same nonce → same R point)")
    assert sig_a[0] == sig_b[0], "r values should match with same nonce"

    # An attacker who sees both signatures can extract the private key
    recovered_key = nonce_reuse_attack(msg_a, sig_a, msg_b, sig_b)

    if recovered_key is not None:
        print(f"\n  ATTACK SUCCESSFUL!")
        print(f"  Recovered private key: {hex(recovered_key)[:20]}...{hex(recovered_key)[-8:]}")
        print(f"  Original private key:  {hex(private_key)[:20]}...{hex(private_key)[-8:]}")
        assert recovered_key == private_key, "Recovered key should match!"
        print(f"  Keys match! The attacker now controls the wallet.")

    # --- Multiple signatures ---
    print("\n[8] Signing and verifying multiple messages...")
    messages = [
        "Hello, blockchain!",
        "The quick brown fox jumps over the lazy dog",
        "",  # Empty message — still works
        "🚀 To the moon!",  # Unicode
    ]

    for msg in messages:
        sig = sign(msg, private_key)
        valid = verify(msg, sig, public_key)
        display = msg if msg else "(empty string)"
        print(f"  '{display}' → valid={valid}")
        assert valid, f"Signature for '{display}' should be valid!"

    print("\n" + "=" * 70)
    print("All checks passed! ECDSA implementation is correct.")
    print("=" * 70)
